### ISSUE TITLE
Passive fight doesn't save

### ISSUE THREAD

**Issue by nivensd** [manigacian/manigacian.github.io#1]
When reloading/reopening the page, the passive fighting purchases must be made again.

**Comment by manigacian** [comment]
Thanks for reporting this - I’ll take a look and see what the problem is

**Comment by manigacian** [comment]
I can see what the problem is, it’s a quick fix, I’ll fix it once I’m at my laptop

**Comment by manigacian** [comment]
This has now been fixed, in version 0.2.2
